### ISSUE TITLE
Track pad is too sensitive for flashlight setting scrolling

### ISSUE THREAD

**Issue by tbascough** [Far-Reach-Co/aethrend-unveiled#3]
in the playerControls switching between flashlight settings goes to quickly from setting 1 to setting 5. It's hard to stop on the middle setting. 

Possible solve: add a few more repeat settings within the Flashlight object's animations
@royalsaltmerchant

**Comment by royalsaltmerchant** [comment]
https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mouse

**Comment by royalsaltmerchant** [comment]
@tbascough here is my suggestions for now: we add some keyboard commands to change the flashlight, and or have a toggle switch in a settings menu to adjust whether or not you want to use the scroll wheel to trigger the flashlight animation or keys

**Comment by royalsaltmerchant** [comment]
Key suggestions : ">" and "<" or 1 - 2 - 3 or "-" and "+"
